alias ls="ls -F --color"
alias tr="transmission-remote 9000 -l"
alias source="source ~/.bashrc"
alias grep="grep -Gi --color=auto"
alias cp-r="sudo dbus-launch gcp -rf"
alias flexget-reload="flexget daemon reload"
alias flexget-log="sudo tail /var/log/upstart/flexget.log --lines=25"
alias tail="tail -f"
alias pid="ps -o comm= -p"                         
alias count="wc -l"
alias npm="sudo npm"
alias nano="sudo nano"
alias vim="sudo vim"
alias apt-get="sudo apt-get"
